### ISSUE TITLE
No value set for `cv_dayViewResource` attribute Error throughing

### ISSUE THREAD

**Issue by Shivtyagi0409** [kizitonwose/Calendar#423] opened 2022-11-25 07:10 UTC
### Library information:
 - Version:2.0.4
 - View  

### Describe the bug**
Caused by: java.lang.IllegalStateException: No value set for `cv_dayViewResource` attribute.

### To Reproduce (if applicable)
On Opening of activity after using WeekCalenderView

### My Layout File
<?xml version="1.0" encoding="utf-8"?>
<androidx.appcompat.widget.LinearLayoutCompat
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/example_1_bg"
    android:clickable="true"
    android:focusable="true"
    android:orientation="vertical"
    tools:context=".view.TestActivity">

    <include
        android:id="@+id/legendLayout"
        layout="@layout/calendar_day_legend_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="10dp"
        android:layout_marginBottom="10dp" />

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.kizitonwose.calendar.view.WeekCalendarView
            android:id="@+id/exOneWeekCalendar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:cv_dayViewResource="@layout/dayview_layout" />

    </FrameLayout>

</androidx.appcompat.widget.LinearLayoutCompat>

### Additional information
E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.extra.TestActivity}: android.view.InflateException: Binary XML file line #30 in com.package:layout/activity_test: Binary XML file line #30 in com.package:layout/activity_test: Error inflating class com.kizitonwose.calendar.view.WeekCalendarView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3685)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.view.InflateException: Binary XML file line #30 in com.package:layout/activity_test: Binary XML file line #30 in com.package:layout/activity_test: Error inflating class com.kizitonwose.calendar.view.WeekCalendarView
     Caused by: android.view.InflateException: Binary XML file line #30 in com.package:layout/activity_test: Error inflating class com.kizitonwose.calendar.view.WeekCalendarView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at com.package.databinding.ActivityTestBinding.inflate(ActivityTestBinding.java:50)
        at com.package.databinding.ActivityTestBinding.inflate(ActivityTestBinding.java:44)
        at com.package.collectiongoal.extra.TestActivity.onCreate(TestActivity.kt:36)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Activity.performCreate(Activity.java:8034)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/UncaughtException: Caused by: java.lang.IllegalStateException: No value set for `cv_dayViewResource` attribute.
        at com.kizitonwose.calendar.view.WeekCalendarView.init(WeekCalendarView.kt:198)
        at com.kizitonwose.calendar.view.WeekCalendarView.<init>(WeekCalendarView.kt:160)
        	... 30 more

**Comment by kizitonwose** [comment] 2022-11-26 14:54
Hey, I cannot reproduce this with the sample app, can you link to a repo where I can reproduce this?

**Comment by kizitonwose** [comment] 2022-12-13 08:10
I will close this, feel free to reopen it if you still have this issue.

**Closed by kizitonwose** 2022-12-13 08:10 UTC
