### ISSUE TITLE
Is it impossible to use this library with MotionLayout?

### ISSUE THREAD

**Issue by Donghyeon0915** [kizitonwose/Calendar#487] opened 2023-08-16 15:24 UTC
### Library information:
 - Version: 2.3.0
 - View or Compose module: view

### Describe the bug**

If you declare CalendarView within MotionLayout, an error occurs as shown below.

like this :
```xml
<androidx.constraintlayout.motion.widget.MotionLayout
        android:id="@+id/ml_calendar_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white"
        app:layoutDescription="@xml/fragment_stats_scene">

        <com.kizitonwose.calendar.view.WeekCalendarView
            android:id="@+id/cl_week_calendar"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginTop="5dp"
            android:padding="10dp"
            android:background="@drawable/bg_rounded_bottom_corner_radius_10"
            android:backgroundTint="@color/white"
            android:alpha="1.0"

            app:cv_dayViewResource="@layout/layout_calendar_day_cell"
            app:layout_constraintBottom_toTopOf="@id/scv_content"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/include_calendar_title_layout"/>
</androidx.constraintlayout.motion.widget.MotionLayout>
```
If you use ConstructLayout instead of MotionLayout, it works normally.

Can't I use this library in MotionLayout?

> Error Log 1
```c
2023-08-17 00:14:11.698 27935-27964/com.example.smiley E/System: Uncaught exception thrown by finalizer
2023-08-17 00:14:11.705 27935-27964/com.example.smiley E/System: java.lang.OutOfMemoryError: Failed to allocate a 8 byte allocation with 1570592 free bytes and 1533KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
        at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:64)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
        at java.lang.Daemons$Daemon.run(Daemons.java:140)
        at java.lang.Thread.run(Thread.java:1012)
```

> Error Log 2
```c
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/.example.smiley: Throwing OutOfMemoryError "Failed to allocate a 9160 byte allocation with 58000 free bytes and 56KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC." (VmSize 17003356 kB)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err: java.lang.OutOfMemoryError: Failed to allocate a 1224 byte allocation with 56360 free bytes and 55KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at java.util.Arrays.copyOf(Arrays.java:3766)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:449)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at java.lang.StringBuilder.append(StringBuilder.java:137)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.graphics.Typeface$Builder.createAssetUid(Typeface.java:714)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.graphics.Typeface$Builder.-$$Nest$smcreateAssetUid(Unknown Source:0)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.graphics.Typeface.findFromCache(Typeface.java:480)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.content.res.ResourcesImpl.loadFont(ResourcesImpl.java:1091)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.content.res.Resources.getFont(Resources.java:545)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.content.res.TypedArray.getFont(TypedArray.java:1048)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.widget.TextView.readTextAppearance(TextView.java:4429)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.widget.TextView.<init>(TextView.java:1404)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.widget.TextView.<init>(TextView.java:1285)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:113)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:108)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:228)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:148)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1678)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1729)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:250)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1083)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1019)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1145)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at com.kizitonwose.calendar.view.internal.ExtensionsKt.inflate(Extensions.kt:9)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at com.kizitonwose.calendar.view.internal.ExtensionsKt.inflate$default(Extensions.kt:8)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at com.kizitonwose.calendar.view.internal.DayHolder.inflateDayView(DayHolder.kt:28)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at com.kizitonwose.calendar.view.internal.WeekHolder.inflateWeekView(WeekHolder.kt:58)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at com.kizitonwose.calendar.view.internal.UtilsKt.setupItemRoot(Utils.kt:56)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at com.kizitonwose.calendar.view.internal.monthcalendar.MonthCalendarAdapter.onCreateViewHolder(MonthCalendarAdapter.kt:61)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at com.kizitonwose.calendar.view.internal.monthcalendar.MonthCalendarAdapter.onCreateViewHolder(MonthCalendarAdapter.kt:30)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7719)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6804)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
2023-08-17 00:14:14.487 27935-27935/com.example.smiley W/System.err:     at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:697)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4307)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4873)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at android.view.View.layout(View.java:24969)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6784)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at androidx.constraintlayout.motion.widget.MotionPaths.setView(MotionPaths.java:640)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at androidx.constraintlayout.motion.widget.MotionController.interpolate(MotionController.java:1286)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at androidx.constraintlayout.motion.widget.MotionLayout.evaluateLayout(MotionLayout.java:3572)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:2960)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at android.view.View.measure(View.java:27720)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at android.view.View.measure(View.java:27720)
2023-08-17 00:14:14.488 27935-27935/com.example.smiley W/System.err:     at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:733)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at android.view.View.measure(View.java:27720)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at android.view.View.measure(View.java:27720)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at android.view.View.measure(View.java:27720)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
2023-08-17 00:14:14.534 27935-27935/com.example.smiley W/System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
```
### To Reproduce (if applicable)

Declare Calendar View within MotionLayout

### Expected behavior (if applicable)

Even if I declare it within MotionLayout, I want it to work normally.

### Screenshots? (if applicable)
- 

### Additional information

I think this is the best library in CalendarView.

If you support MotionLayout, I think it will be an even better library.

Can you modify it to support MotionLayout?

**Comment by kizitonwose** [comment] 2023-08-31 07:45
I added MotionLayout in `example_7_fragment.xml` and it works.

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:clickable="true"
    android:focusable="true"
    android:orientation="vertical"
    tools:context=".view.Example7Fragment">

    <com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay">

        <androidx.appcompat.widget.Toolbar
            android:id="@+id/exSevenToolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            app:popupTheme="@style/AppTheme.PopupOverlay" />

        <androidx.constraintlayout.motion.widget.MotionLayout
            android:id="@+id/ml_calendar_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layoutDescription="@xml/example_7_fragment_scene">

            <com.kizitonwose.calendar.view.WeekCalendarView
                android:id="@+id/exSevenCalendar"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:cv_dayViewResource="@layout/example_7_calendar_day"
                app:cv_daySize="seventhWidth"
                app:cv_orientation="horizontal" />
        </androidx.constraintlayout.motion.widget.MotionLayout>

    </com.google.android.material.appbar.AppBarLayout>

</LinearLayout>
```
<img src="https://github.com/kizitonwose/Calendar/assets/15170090/897e3de6-6148-4d78-86f5-1a573b993b5c" width="300">

---

So it looks like the issue you have is not with MotionLayout. If you can reproduce it in the sample project, I'd be happy to take a look.

**Comment by Donghyeon0915** [comment] 2023-09-02 11:55
@kizitonwose 
Sorry, it wasn't just about declaring a calendar view in MotionLayout, it was about the scope of the calendar.

In ConstructLayout, there was no performance degradation when the date range was 240 months, but in MotionLayout, there was a significant performance degradation in the process of creating a date cell.

Specifying a date range of about 3 months causes a delay at the time of initial creation, and specifying 240 months as the code above causes an OutOfMemoryError.

Didn't this happen in your project?

**Comment by kizitonwose** [comment] 2023-09-11 09:20
I just changed the setup to 1000 months (500 on each side) and there was no performance degradation or OOM error:

```kotlin
binding.exSevenCalendar.setup(
    startDate = currentMonth.minusMonths(500).atStartOfMonth(),
    endDate = currentMonth.plusMonths(500).atEndOfMonth(),
    firstDayOfWeek = firstDayOfWeekFromLocale(),
)
```

**Comment by kizitonwose** [comment] 2023-10-03 05:17
I'll close this issue, please reopen it if you need further assistance and it'd be best to try and reproduce the issue in the sample project to ensure that it is not something in your code.

**Closed by kizitonwose** 2023-10-03 05:17 UTC
