### ISSUE TITLE
Jerking when scrolling the calendar

### ISSUE THREAD

**Issue by KamilKhametov** [kizitonwose/Calendar#522] opened 2024-01-09 13:46 UTC
### Library information:
 - Version: 2.3.0
 - View or Compose module: view

### Describe the bug**
when scrolling through the calendar, there is a jerking, watch the video recording

### Expected behavior (if applicable)
Smooth calendar scrolling, no twitching

### Screenshots? (if applicable)
https://github.com/kizitonwose/Calendar/assets/58626314/6af2c515-3494-429d-8761-7ba70b84ea01

### Additional information
below the code of the fragment in which this calendar is implemented
https://gist.github.com/KamilKhametov/6a0dd9d00ab510d0cbad40d9a1bad54b

**Comment by kizitonwose** [comment] 2024-01-10 08:10
Your binding logic looks fine, does the flash still happen if you just initialize the calendar without showing any information on it? Also, does it happen if you put it in a full fragment instead of a dialog fragment?

**Comment by KamilKhametov** [comment] 2024-01-10 13:43
> Your binding logic looks fine, does the flash still happen if you just initialize the calendar without showing any information on it? Also, does it happen if you put it in a full fragment instead of a dialog fragment?

Yes, before that I implemented it without logic and in a full fragment, and it still jerking

**Comment by kizitonwose** [comment] 2024-01-17 12:02
I have no idea why this would happen because the sample project looks line. Can you share a minimal sample project where I can reproduce the issue?

**Comment by kizitonwose** [comment] 2024-02-17 10:37
I will close this, feel free to reopen it if you have more questions.

**Closed by kizitonwose** 2024-02-17 10:37 UTC
