### ISSUE TITLE
App crashing while using HorizontalCalendar

### ISSUE THREAD

**Issue by simar-mmf** [kizitonwose/Calendar#524] opened 2024-01-17 10:24 UTC
### Library information:
 - Version: 2.3.0
 - View or Compose module: Compose

Currently using compose bom 2023.03.00, which uses compose:ui version 1.4.0.

`java.lang.NoSuchMethodError: No static method 
SnapLayoutInfoProvider(Landroidx/compose/foundation/lazy/LazyListState;Lkotlin/jvm/functions/Function3;)Landroidx/compose/foundation/gestures/snapping/SnapLayoutInfoProvider; in
class Landroidx/compose/foundation/gestures/snapping/LazyListSnapLayoutInfoProviderKt; or its super classes (declaration of                                                                                              'androidx.compose.foundation.gestures.snapping.LazyListSnapLayoutInfoProviderKt' appears in`

I tried using other combinations of the compose ui and this library.
The crash is not found in some of the cases, but the horizontal calendar does not respond to touch gestures in that case.

**Comment by kizitonwose** [comment] 2024-01-17 12:00
My guess is that a transitive dependency is updating your compose to version 1.5.x, you will probably notice that the issue is fixed with calendar library version 2.4.x

**Comment by myounis97** [comment] 2024-01-30 15:54
@kizitonwose hello, it is happening on the latest compose version 2024.01.00

**Comment by kizitonwose** [comment] 2024-02-13 10:06
Please use version [2.5.0](https://github.com/kizitonwose/Calendar/releases/tag/2.5.0)

**Closed by kizitonwose** 2024-02-13 10:06 UTC

**Comment by navneetpal01** [comment] 2024-03-04 09:28
Thanks it worked
