### ISSUE TITLE
Throw `AbstractMethodError` when scrolling calendar

### ISSUE THREAD

**Issue by dylan-kwon** [kizitonwose/Calendar#453] opened 2023-03-06 16:34 UTC
### Library information:
 - Version: 2.2.0
 - View or Compose module: Compose

### Describe the bug**
`java.lang.AbstractMethodError: abstract method "float androidx.compose.foundation.gestures.snapping.SnapLayoutInfoProvider.calculateSnapStepSize(androidx.compose.ui.unit.Density)"`

### To Reproduce (if applicable)
1. Just scroll to next or prev month.

It works normally in versions below 2.1.1.

**Comment by kizitonwose** [comment] 2023-03-09 08:12
What version of compose do you have?

**Comment by dylan-kwon** [comment] 2023-03-09 08:44
compose.compiler `1.4.3`
material3 `1.1.0-alpha08`
etc `1.4.0-rc01`

**Comment by kizitonwose** [comment] 2023-03-10 09:34
> etc 1.4.0-rc01 

I assume this is compose UI?

**Comment by dylan-kwon** [comment] 2023-03-10 11:11
yes

**Comment by kizitonwose** [comment] 2023-03-10 11:20
That would be great, thanks. Although compose 1.4 isn't officially supported yet.

**Comment by dylan-kwon** [comment] 2023-03-13 02:33
thank you
Are there any plans or timelines for compose 1.4 support?

**Comment by arijit4** [comment] 2023-03-25 13:06
@dylan-kwon did you find any workaround? I'm also facing this issue. I upgraded my compose version to 1.4.1 and this happened.

**Comment by kizitonwose** [comment] 2023-03-25 17:22
I bumped compose UI to 1.4 in [this branch](https://github.com/kizitonwose/Calendar/tree/compose_1_4) but could not reproduce this crash, could someone provide more info regarding usage/calendar setup etc.

**Comment by arijit4** [comment] 2023-03-26 03:08
@kizitonwose I'm using a `HorizontalCalender` which is showing 12 months. 1st month is rendered fine. As soon as I scroll to the 2nd month, the app crashes and logs the error @dylan-kwon has mentioned.

**Comment by kizitonwose** [comment] 2023-03-26 13:50
This is now fixed in the latest [library snapshot](https://s01.oss.sonatype.org/content/repositories/snapshots/com/kizitonwose/calendar/). 
Please use the snapshot and check that it works as expected.

Snapshot url: `maven { url 'https://s01.oss.sonatype.org/content/repositories/snapshots/' }`
Snapshot artifact: ` implementation 'com.kizitonwose.calendar:compose:2.2.1-SNAPSHOT'`

I will release it this week.

**Comment by dylan-kwon** [comment] 2023-03-27 01:03
@kizitonwose I use this snapshot version and the problem is solved.

**Comment by arijit4** [comment] 2023-03-27 02:54
@kizitonwose I have obe more suggestion if you can make it work. What if the calender is snapped to the middle of screen, not to the start?

**Comment by kizitonwose** [comment] 2023-04-02 10:05
Version 2.3.0 is now released with the fix.

**Closed by kizitonwose** 2023-04-02 10:05 UTC
